tailwind.config = {
    darkMode: "class",
    theme: {
      extend: {
        "colors": {
                "on-primary": "#ffffff",
                "surface-container-low": "#f1f4f6",
                "on-secondary-container": "#596376",
                "on-surface-variant": "#5a403e",
                "inverse-on-surface": "#eef1f3",
                "surface-tint": "#b52426",
                "error": "#ba1a1a",
                "tertiary-fixed": "#91f8b8",
                "tertiary-container": "#007947",
                "primary": "#a2141b",
                "background": "#f7fafc",
                "on-secondary": "#ffffff",
                "on-primary-fixed": "#410003",
                "tertiary-fixed-dim": "#74db9d",
                "primary-fixed": "#ffdad6",
                "outline-variant": "#e2bebb",
                "error-container": "#ffdad6",
                "outline": "#8e706d",
                "on-surface": "#181c1e",
                "on-tertiary": "#ffffff",
                "on-primary-container": "#ffe4e1",
                "surface-dim": "#d7dadc",
                "tertiary": "#005e36",
                "on-secondary-fixed": "#121c2c",
                "secondary-fixed-dim": "#bdc7dc",
                "inverse-surface": "#2d3133",
                "surface-bright": "#f7fafc",
                "on-primary-fixed-variant": "#920212",
                "on-tertiary-fixed-variant": "#00522f",
                "on-background": "#181c1e",
                "on-error": "#ffffff",
                "secondary-fixed": "#d9e3f9",
                "surface-container": "#ebeef0",
                "on-tertiary-fixed": "#002110",
                "on-error-container": "#93000a",
                "secondary-container": "#d6e0f6",
                "primary-container": "#c53030",
                "on-secondary-fixed-variant": "#3d4759",
                "primary-fixed-dim": "#ffb3ad",
                "secondary": "#555f71",
                "inverse-primary": "#ffb3ad",
                "surface-container-high": "#e5e9eb",
                "surface": "#f7fafc",
                "on-tertiary-container": "#98ffbf",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#e0e3e5",
                "surface-variant": "#e0e3e5"
        },
        "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
        },
        "spacing": {
                "md": "16px",
                "xs": "4px",
                "container-max": "1200px",
                "unit": "4px",
                "sm": "8px",
                "gutter": "24px",
                "lg": "24px",
                "xl": "40px"
        },
        "fontFamily": {
                "headline-lg-mobile": ["Hanken Grotesk"],
                "label-sm": ["JetBrains Mono"],
                "headline-md": ["Hanken Grotesk"],
                "headline-lg": ["Hanken Grotesk"],
                "label-md": ["JetBrains Mono"],
                "display-lg": ["Hanken Grotesk"],
                "body-md": ["Hanken Grotesk"],
                "body-lg": ["Hanken Grotesk"]
        },
        "fontSize": {
                "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
        }
},
    },
  }
